### ISSUE TITLE
No module named 'pytorch_lightning.utilities.apply_func'

### ISSUE THREAD

**Issue by DanTaranis** [Lightning-Universe/lightning-flash#1621]
## 🐛 Bug

the line of code "import flash" results in '''No module named 'pytorch_lightning.utilities.apply_func''''

### To Reproduce
 pip install lightning-flash

### Environment

 - OS (e.g., Linux): ubuntu 20
 - Python version: (3.9)
 - PyTorch/Lightning/Flash Version (e.g., 1.10/1.5/0.7): (2.0.1/2.0.4/0.8.1.post0)
 - GPU models and configuration: (has 4 gpus)
 - Any other relevant information:

**Comment by Borda** [comment]
this shall be fixed with latest `0.8.2` :rabbit:

**Comment by amorehead** [comment]
Sadly, I am still encountering this issue with `lightning==2.0.9` and `pytorch_lightning==2.0.9`.

**Comment by Borda** [comment]
Mind try install Flash from source/master?

**Comment by amorehead** [comment]
Using `pip install 'git+https://github.com/Lightning-Universe/lightning-flash.git'` sadly gave the same result.
